### ISSUE TITLE
[Nexus3] Failed to update nexus3 3.33 to 3.38.1

### ISSUE THREAD

**Issue by GabrielAmaral** [stevehipwell/helm-charts#518]
Hi,

I'm trying to update my nexus3 from 3.33 to 3.38.1, but I received an error "Could not update the root password". 

I've connected SSH in the pod and had tryeid to exec a curl command to localhost:8081 and I received 503.

**Comment by stevehipwell** [comment]
@GabrielAmaral I'm AFK this week so will have to look at this next week. I assume that as you're updating that you haven't tried to switch to a StatefulSet?

**Comment by stevehipwell** [comment]
@GabrielAmaral are you trying to use the `StatefulSet` mode? If so firstly you can't update between the `Deployment` mode & the `StatefulSet` mode, and secondly there is currently a bug (#516) with the `StatefulSet` implementation. If you're not then I'll need more information to look into this further.

**Comment by GabrielAmaral** [comment]
Hi @stevehipwell , we found the root cause of our problem.

It appears to be something related to the admin/root password.

I manually updated the admin.password in orientDB like this document:

https://support.sonatype.com/hc/en-us/articles/213467158-How-to-reset-a-forgotten-admin-password-in-Nexus-3-x

And after that we configured /nexus-data/admin.password with the value "admin123", then we did the update and it worked fine.

**Comment by stevehipwell** [comment]
@GabrielAmaral if you're using the chart to configure Nexus you need to either be using strict IaC or keep both systems in sync; I'm going to close the issue as I don't this this is a chart issue.

**Comment by timdeluxe** [comment]
Posting here because my issue is related to this:
Everytime Nexus is restarted, it creates the admin.password file with a newly generated password. The script in the helm chart then fails, because it can not login, since the real password of the admin was already changed and does not fit to the one in the admin.password file.
According to what i read the admin.password file is only for initial setup, so i guess some flag somewhere is missing, which tells it to not create it on each startup anymore. Does someone know more?

**Comment by stevehipwell** [comment]
@timdeluxe could you create a new issue with your specific scenario in it including the values you're passing into the Helm chart?

**Comment by timdeluxe** [comment]
@stevehipwell Sure, see #596
